### ISSUE TITLE
 Still connecting to unix:///csi/csi.sock ,

### ISSUE THREAD

**Issue by ghost** [huaweicloud/huaweicloud-csi-driver#1]
Hi I have deployed CFCR Kubernetes cluster on Huawei cloud and now I want to use CSI driver for which I ma facing issue>

 E0828 14:19:05.108323       1 connection.go:129] Lost connection to unix:///csi/csi.sock. F0828 14:19:05.108459       1 connection.go:91] Lost connection to CSI driver, exiting

**Comment by chengxiangdong** [comment]
I need to know more details, but ghost...

**Comment by chengxiangdong** [comment]
I will close this issue.
If the problem persists, you can submit a new issue.
