### ISSUE TITLE
[obsfs with CSI driver] Missing volume metric

### ISSUE THREAD

**Issue by MrLuje** [huaweicloud/huaweicloud-csi-driver#110]
Hello,

I'm not totally sure this is the correct repository for https://support.huaweicloud.com/intl/en-us/usermanual-cce/cce_01_0066.html
We have been using OBS mounted as PVC and we noticed that metrics are not reported to kubelet (metric `kubelet_volume_stats_capacity_bytes` missing for this volume).

PVC is declared with :
```sh
metadata:
  name: cce-obs-datagateway
  annotations:
    csi.storage.k8s.io/fstype: obsfs
    volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
```

This is the mount as seen by the Pod :
```bash
bash-4.4$ df -h | grep storage
obsfs                                                                                             256T     0  256T   0% /work/storage
```

No prometheus metrics reported with : 
```yaml
kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="cce-obs-datagateway"}

=> empty
```

Thanks

**Comment by chengxiangdong** [comment]
This repository is not for `CCE`, it is for a custom Kubernetes clusters. 
For `CSI` issues in `CCE`, please submit Service Tickets on HUAWEI CLOUD for consultation.
