### ISSUE TITLE
sfsturbo无法创建pv，提示err: Missing input for argument [VpcID]

### ISSUE THREAD

**Issue by monkeydzhao** [huaweicloud/huaweicloud-csi-driver#114]
使用官方example，创建sc和pvc，无法创建pv。但是根据csi-provisioner日志，grpc请求中携带了VpcID
csi-provisioner 日志
I0527 02:45:44.798204       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"sfsturbo-pvc-dynamic", UID:"d8a2af89-3080-4e86-803d-918943753b0f", APIVersion:"v1", ResourceVersion:"4703379", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/sfsturbo-pvc-dynamic"
I0527 02:45:44.798177       1 connection.go:184] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.sfsturbo.csi.huaweicloud.com/zone":"xxxxxxx"}}],"requisite":[{"segments":{"topology.sfsturbo.csi.huaweicloud.com/zone":"xxxxxxxxx"}}]},"capacity_range":{"required_bytes":10737418240},"name":"pvc-d8a2af89-3080-4e86-803d-918943753b0f","parameters":{"VpcID":"xxxxxxxxxxxxxx","csi.storage.k8s.io/pv/name":"pvc-d8a2af89-3080-4e86-803d-918943753b0f","csi.storage.k8s.io/pvc/name":"sfsturbo-pvc-dynamic","csi.storage.k8s.io/pvc/namespace":"default","shareType":"STANDARD"},"volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
I0527 02:45:45.014996       1 connection.go:186] GRPC response: {}
I0527 02:45:45.015041       1 connection.go:187] GRPC error: rpc error: code = Internal desc = Failed to create share, err: Missing input for argument [VpcID]
I0527 02:45:45.015059       1 controller.go:764] CreateVolume failed, supports topology = true, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = Failed to create share, err: Missing input for argument [VpcID]

**Comment by chengxiangdong** [comment]
在 `cloud-config` 配置中，需要配置vpcID

![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/8384921/3ccc7c95-426e-43b3-abe2-b2d8cdc7396d)

https://github.com/huaweicloud/huaweicloud-csi-driver/blob/51274166f10bd184cc588dd63ccb5dafbbf4aab0/deploy/sfsturbo-csi-plugin/cloud-config#LL14C1

**Comment by monkeydzhao** [comment]
> 在 `cloud-config` 配置中，需要配置VPC ID
> 
> ![image](https://user-images.githubusercontent.com/8384921/241363326-3ccc7c95-426e-43b3-abe2-b2d8cdc7396d.png)
> 
> https://github.com/huaweicloud/huaweicloud-csi-driver/blob/51274166f10bd184cc588dd63ccb5dafbbf4aab0/deploy/sfsturbo-csi-plugin/cloud-config#LL14C1

是这样的，我上午已经修改，现在已经可以正常使用，多谢。
