### ISSUE TITLE
华为云私有云环境下启动csi-evs-plugin报错

### ISSUE THREAD

**Issue by monkeydzhao** [huaweicloud/huaweicloud-csi-driver#116]
I0609 08:08:47.592304       1 config.go:36] load config from file: /etc/evs/cloud-config
F0609 08:08:55.599362       1 main.go:105] Failed to load cloud config: Get "https://iam.myhuaweicloud.com:443/v3/projects?name=lt-hlw": dial tcp: lookup iam.myhuaweicloud.com on 10.96.0.10:53: server misbehaving

**Comment by chengxiangdong** [comment]
> dial tcp: lookup iam.myhuaweicloud.com on 10.96.0.10:53: server misbehaving

看上去是 DNS 解析失败，有使用自己搭建的 DNS 服务吗？

**Comment by chengxiangdong** [comment]
抱歉，没注意看你说的是私有云，私有云在 `cloud-config` 中必须配置 `cloud` 和 `auth-url` 字段。
注意：修改 cloud-config secret 后需要重启 csi-evs-controller 和 csi-evs-node。

cloud-config 文档：https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/cloud-config.md

**Comment by monkeydzhao** [comment]
> 抱歉，没注意看你说的是私有云，私有云在 `cloud-config` 中必须配置 `cloud` 和 `auth-url` 字段。 注意：修改 cloud-config secret 后需要重启 csi-evs-controller 和 csi-evs-node。
> 
> cloud-config 文档：https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/cloud-config.md
> 
> 另外，因为私有云和公有云的 API 有一定版本差异，请做好充分的验证。

你好，请问这个cloud和auth-url 怎么获取呢

**Comment by chengxiangdong** [comment]
> 你好，请问这个cloud和auth-url 怎么获取呢

因为 `cloud` 和 `auth-url` 与网络环境有较大的关系，建议您联系一下华为云的支撑人员

**Comment by monkeydzhao** [comment]
> > 你好，请问这个cloud和auth-url 怎么获取呢
> 
> 因为 `cloud` 和 `auth-url` 与网络环境有较大的关系，建议您联系一下华为云的支撑人员

你好，这个cloud和auth-url 我已经配置，现在还有个问题，因为私有集群是自签证书，所以请求auth-url 报错，请问是否支持不校验证书

**Comment by chengxiangdong** [comment]
可以修改集群配置关闭校验，不过这会降低集群安全系数，不建议这么操作。

**Comment by chengxiangdong** [comment]
后续建议联系支撑人员，他们会找到我们的，那样效率高一些。

**Comment by chengxiangdong** [comment]
该问题通过内部支撑人员解决，我先关闭了。
如还有需要去，请重新开启。
