### ISSUE TITLE
使用csi 插件扩容evs 时不生效，需要手动在节点运行 resize2fs命令扩容才能生效

### ISSUE THREAD

**Issue by huntkalio** [huaweicloud/huaweicloud-csi-driver#117]
1环境: 华为云ECS自建K8S , K8S 版本 1.20.11
2.插件: https://github.com/huaweicloud/huaweicloud-csi-driver
3.插件版本: swr.cn-north-4.myhuaweicloud.com/k8s-csi/evs-csi-plugin:v0.1.6
4.问题描述: 
1）使用华为云 evs csi 插件创建pvc , csi 插件创建磁盘并挂载到对应pod正常。
2）修改 pvc 的 磁盘大小 resources.requests.storage 参数。从20G 修改到 21G, 22G, 25G;
3）csi-resizer 日志提示修改成功，华为云控制台看对应实例也线上磁盘扩容成功。
4）但对应机器和pod上查看磁盘大小未发生变化（df查看）。即使删除pod重新挂载也显示大小未发生变化了；
5）登录对应挂载节点手动运行resize2fs命令扩容才能生效
5.其他： 查看pv/pvc 显示扩容成功；csi-resizer日志显示扩容成功；evs-csi-plugin日志显示获取磁盘大小未改变;  k8s 未开启CSI Snapshotter

**Comment by chengxiangdong** [comment]
你这边应该是两个问题：
1、EVS 完成扩容后，在系统中的容量没有变化，需要手动运行命令后才能生效。
经过分析，这是一个bug导致的。

2、k8s 未开启 CSI Snapshotter
如果要使用快照功能，需要在集群中安装扩展插件，参考： https://github.com/kubernetes-csi/external-snapshotter

**Comment by chengxiangdong** [comment]
修复后的版本已经发布了，请使用 `v0.1.7` （swr.cn-north-4.myhuaweicloud.com/k8s-csi/evs-csi-plugin:v0.1.7） 版本的镜像。
如还是有问题，请再打开此 issue 或则创建一个新的。

**Comment by huntkalio** [comment]
> 修复后的版本已经发布了，请使用 `v0.1.7` （swr.cn-north-4.myhuaweicloud.com/k8s-csi/evs-csi-plugin:v0.1.7） 版本的镜像。 如还是有问题，请再打开此 issue 或则创建一个新的。

刚测试已经解决这个问题了，感谢。
