### ISSUE TITLE
Problem with VolumeSnaphots

### ISSUE THREAD

**Issue by artemnikitin2023** [huaweicloud/huaweicloud-csi-driver#125]
Hello.
I've installed the driver and his dependencies (such as csi-external-snapshotter) and trying to create VolumeSnapshots.
I'm trying to make a VolumeSnapshot of an EVS backed PVC\PV that is attached to a Pod (EVS status In-Use), but got an error message that says that EVS volume must be in a Available state (detached from any Pods), eror code EVS.5400.
Is it possible to make a volume snapshots of an In-Use EVS volume via this driver?
p.s. I don't have this problem in a CCE cluster, but it uses a different driver...

Please help.
Regards.

**Comment by chengxiangdong** [comment]
Hi, after installing the xxx plugin, the EVS image functionality is working properly. 
I checked the error code, `EVS.5400`: API call parameter format error. 

Can you provide the logs of csi-evs-controller as follows:
```
kubectl logs pod/csi-evs-controller-xxxx -c evs-csi-provisioner -n kube-system > csi.log
```
Please provide the logs for further investigation. 
Thank you!

**Comment by artemnikitin2023** [comment]
Hello!
I've updated the driver version and problem is gone.
Thank you!
