### ISSUE TITLE
云平台支持人员无法找到此插件

### ISSUE THREAD

**Issue by zhujiaxin** [huaweicloud/huaweicloud-csi-driver#132]
您好，我们本地为HCS821版本，我们在编辑`cloud_config`文件的时候遇到一些问题。
根据此[issue](https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116)中提到需要找华为云支持人员，
我找到了政企400的同事，他们反馈找不到这个插件，也找不到对应的技术人员。
请问需要如何让后端找到你们？

**Comment by zhujiaxin** [comment]
@chengxiangdong 麻烦看一下此issue.

**Comment by niuzhenguo** [comment]
这个是华为公有云的插件，没有HCS的支持

**Comment by zhujiaxin** [comment]
这个(issue)[https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116]中提到的私有云不是HCS吗？
@niuzhenguo

**Comment by chengxiangdong** [comment]
> 这个[issue](https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116)中提到的私有云不是HCS吗？ @niuzhenguo

这个插件是适配华为公有云的，因为私有云的API与公有云的有一定的差异，所以不能完成兼容私有云。
在私有云上如何使用CSI插件，建议联系对应支持人员或者解决方案。

**Comment by zhujiaxin** [comment]
> 对应支持人员或者解决方案。

我联系了政企的400，结果他说找不到您，能指导一下让他们找哪条产品线的支持人员吗？

**Comment by zhujiaxin** [comment]
> > 这个[issue](https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116)中提到的私有云不是HCS吗？ @niuzhenguo
> 
> 这个插件是适配华为公有云的，因为私有云的API与公有云的有一定的差异，所以不能完成兼容私有云。 在私有云上如何使用CSI插件，建议联系对应支持人员或者解决方案。


我联系了政企的400，结果他说找不到您，能指导一下让他们找哪条产品线的支持人员吗？

**Comment by chengxiangdong** [comment]
> > > 这个[issue](https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116)中提到的私有云不是HCS吗？ @niuzhenguo
> > 
> > 
> > 这个插件是适配华为公有云的，因为私有云的API与公有云的有一定的差异，所以不能完成兼容私有云。 在私有云上如何使用CSI插件，建议联系对应支持人员或者解决方案。
> 
> 我联系了政企的400，结果他说找不到您，能指导一下让他们找哪条产品线的支持人员吗？

抱歉，给您带来麻烦了。我可以试着和他们沟通一下，可以让他通过内部welink搜索`chengxiangdong`，部门所属华为云的就是我，没有其他同事重名。

**Comment by zhujiaxin** [comment]
> > > > 这个[issue](https://github.com/huaweicloud/huaweicloud-csi-driver/issues/116)中提到的私有云不是HCS吗？ @niuzhenguo
> > > 
> > > 
> > > 这个插件是适配华为公有云的，因为私有云的API与公有云的有一定的差异，所以不能完成兼容私有云。 在私有云上如何使用CSI插件，建议联系对应支持人员或者解决方案。
> > 
> > 
> > 我联系了政企的400，结果他说找不到您，能指导一下让他们找哪条产品线的支持人员吗？
> 
> 抱歉，给您带来麻烦了。我可以试着和他们沟通一下，可以让他通过内部welink搜索`chengxiangdong`，部门所属华为云的就是我，没有其他同事重名。

感谢，我尝试让400联系您。
