### ISSUE TITLE
error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/obs.csi.huaweicloud.com/csi.sock: connect: connection refused"

### ISSUE THREAD

**Issue by jsczrangel** [huaweicloud/huaweicloud-csi-driver#134]
![image](https://github.com/huaweicloud/huaweicloud-csi-driver/assets/35262775/9ca8e6e1-4f07-4198-a5d4-ff90f8efc41a)
挂载时报错，pvc报错csi.sock: connect: connection refused，追踪到pod obs-csi-plugin的报错如图

**Comment by chengxiangdong** [comment]
看日志是鉴权失败导致启动失败，貌似是cloud-config中配置了加密的ak/sk后导致的，cloud-config中的ak/sk不能加密。
