### ISSUE TITLE
Port conflict when deploy evs-csi-plugin

### ISSUE THREAD

**Issue by hardenchant** [huaweicloud/huaweicloud-csi-driver#136]
When I try deploy [evs-csi-plugin](https://github.com/huaweicloud/huaweicloud-csi-driver/tree/master/deploy/evs-csi-plugin/kubernetes), I realized that csi-evs-controller and csi-evs-plugin have `hostNetwork: true` for both, but they also both try to expose port 9808 for healthcheck. It proceed to conflict when I deploy controller to node with driver or vice versa.
If i change that port to another one, than i got error at logs from plugin binary that port already in use (binary have no args for specifying port for liveness probe at --help).

**Comment by hardenchant** [comment]
Moreover, that port already in use by our cri – cri-o for healthz, and i had to remove hostNetwork: true from both.

**Comment by chengxiangdong** [comment]
Adding `hostNetwork: true` was intended to address the issue of being unable to access ECS metadata within the Pod by sharing the host's network with the Pod. However, this doesn't seem to be an optimal solution.

We will first remove the `hostNetwork: true` .
