### ISSUE TITLE
Able to deploy huaweicloud csi driver but not able run the example app

### ISSUE THREAD

**Issue by ghost** [huaweicloud/huaweicloud-csi-driver#2]
Example App failing after creating storage class
 kubectl logs pod/csi-sfs-controller-7486c68b77-qn9z2 -c sfs-csi-plugin  -c sfs-csi-plugin
ype:"ext4" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] map[] map[] <nil> <nil> {} [] 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x794056]

**Comment by chengxiangdong** [comment]
Hi @ghost,
We have released a new version of SFS and updated [documentation](https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/sfs/sfs.md).
Please try it with the new version.

**Comment by chengxiangdong** [comment]
The author's account has been deleted, i will close this issue.
If the problem persists, you can submit a new issue.
