### ISSUE TITLE
How can we create SFS-Turbo PVC in Linux(NFS) or Windows (CIFS) using this CSI Driver 

### ISSUE THREAD

**Issue by sawan-talwar** [huaweicloud/huaweicloud-csi-driver#3]
How can we create SFS-Turbo PVC in Linux(NFS) or Windows (CIFS) using this CSI Driver

**Comment by chengxiangdong** [comment]
@sawan-talwar  SFS-Turbo CSI plugin will be supported by the end of this year.

**Comment by chengxiangdong** [comment]
The SFS-Turbo CSI plugin has been released, see [Huawei Cloud SFS Turbo CSI Driver](https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/sfsturbo/sfsturbo.md) for details.

**Comment by chengxiangdong** [comment]
Current version does not support the Windows platform.

**Comment by chengxiangdong** [comment]
/close
This issue solved, close.
If this issue still exists, please open it with `/reopen`.
