### ISSUE TITLE
[Question] Is there any plan to support OBS

### ISSUE THREAD

**Issue by freesky-edward** [huaweicloud/huaweicloud-csi-driver#4]
I am not sure whether is the right place to ask one question is there any plan to support provisionning OBS buckets as the bankend storage of pod, or it has been existing somewhere. very appreciated any response

**Comment by jumping** [comment]
You can use OBS with CCE in some regions. Please check the console of CCE.

**Comment by niuzhenguo** [comment]
@freesky-edward OBS CSI plugin will be supported by the end of this year.

**Comment by chengxiangdong** [comment]
Hi @freesky-edward, 
the OBS CSI plugin has been released, see [Huawei Cloud OBS CSI Driver](https://github.com/huaweicloud/huaweicloud-csi-driver/blob/master/docs/obs/obs.md) for details.
