### ISSUE TITLE
[OCP4][SFS with CSI driver] Missing volume metric

### ISSUE THREAD

**Issue by davidasaadmikhailtadros** [huaweicloud/huaweicloud-csi-driver#46]
Hello,

We recently discovered a problem with the SFS volumes created with the new CSI driver – we are not able to see how much of the volume is being used.

To give some context, earlier this year, at the beginning of March, due to the Openshift cluster upgrade to version 4.8 we were forced to also update the SFS driver - previously we were using the “external.k8s.io/sfs” provisioner and we switched to “sfs.csi.huaweicloud.com” (version 1.3.2 of sfs-csi-plugin).

More details about the problem:

Every new SFS volume we create will not show the “used” size anymore
![image](https://user-images.githubusercontent.com/22997968/196893649-ba2ac1a2-87f4-4b78-b576-1c8889434b1e.png)
If we rsh into the pod using this volume, we can see that there’s some space being used:
![image](https://user-images.githubusercontent.com/22997968/196893832-bbe55101-654e-425a-9f73-87a15e9a7d4e.png)
![image](https://user-images.githubusercontent.com/22997968/196893922-656a1145-84a3-4ccb-b858-6439678914db.png)
What we expect to see, if we check a volume created with the old provisioner we can see the information:
![image](https://user-images.githubusercontent.com/22997968/196894046-bd4b7e63-5aac-4dee-b13a-21bb2102a1f1.png)

It seems that Openshift GUI uses the “kubelet_volume_stats_used_bytes” metric to populate the “used” field, which is empty for the volumes created with the new provisioner. We observed this on both DI and PR environments, running Openshift versions 4.8 and 4.10.

Can you please check and advise?

**Comment by chengxiangdong** [comment]
This issue has been fixed, close it.
If the problem persists, you can reopen it.
