### ISSUE TITLE
This parameter is redundant, please optimize and remove it later.

### ISSUE THREAD

**Issue by chengxiangdong** [huaweicloud/huaweicloud-csi-driver#66]
This parameter is redundant, please optimize and remove it later.

_Originally posted by @chengxiangdong in https://github.com/huaweicloud/huaweicloud-csi-driver/pull/65#discussion_r1021043165_
      
assign to @deer-hang

**Comment by deer-hang** [comment]
This parameter will be used for setting bucket capacity, should be retained.
