### ISSUE TITLE
EVS CSI Error: Unable to find instance

### ISSUE THREAD

**Issue by Carlimeunier** [huaweicloud/huaweicloud-csi-driver#78]
Hello,

Environement: 
- VPC
- EVS CSI plugin

After installing evs csi successfully, pvc can be created with pv 

=>  kubectl  get pvc 
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
evs-normal-pvc   Bound    pvc-a572c122-2baf-4e88-b28e-96890f131103   10Gi       RWX            evs-sc         7m30s

But not able to use it in pod. Here is the following error message : 
 
=> kubectl describe po
  Warning  FailedAttachVolume  15s (x7 over 50s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a572c122-2baf-4e88-b28e-96890f131103" : rpc error: code = NotFound desc = Error, ECS instance 0219e192-df26-491b-afe3-8ba2ef99f87a does not exist

The provisioner tries to find instance to mount the volume but it is not able to find it.

Please help

**Comment by chengxiangdong** [comment]
Hi Carlimeunier,
please check whether the ECS exists at the console, and ensure that the region of the ECS is the same as that in `cloud-config`
